### ISSUE TITLE
w2wc segfaults with SO

### ISSUE THREAD

**Issue by eassmann** [wien2wannier/wien2wannier#10]
As reported on the [mailing list,](http://www.mail-archive.com/wien%40zeus.theochem.tuwien.ac.at/msg12925.html) and independently via private e-mail, `w2wc` sometimes fails with a segfault in cases with spin-orbit coupling:

```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
w2wc               0000000000423B86  almgen_                   120  almgen.F
w2wc               0000000000418ECF  l2mmn_                     72  l2mmn.f
w2wc               00000000004179BA  MAIN__                    226  main.f
w2wc               0000000000404A2C  Unknown               Unknown  Unknown
libc.so.6          00002B0BAE7F4C36  Unknown               Unknown  Unknown
w2wc               0000000000404909  Unknown               Unknown  Unknown
46.906u 0.116s 0:47.15 99.7%    0+0k 0+160io 0pf+0w
```

The cited part of `almgen.f` is

```
      IF (nlo.ne.0) THEN
       i=n-(nlo+nlon)
       DO L=0,LoMAX
        mirf=n_rad(l)
        DO jlo=1,ilo(l)
         DO jneq=1,mult(jatom)
          DO M1=-l,l
           i=i+1
           BK(1)=BKX(I)*BR1(1,1)+BKY(I)*BR1(1,2)+BKZ(I)*BR1(1,3)
           BK(2)=BKX(I)*BR1(2,1)+BKY(I)*BR1(2,2)+BKZ(I)*BR1(2,3)
           BK(3)=BKX(I)*BR1(3,1)+BKY(I)*BR1(3,2)+BKZ(I)*BR1(3,3)
```

**Comment by eassmann** [comment]
This bug was never reproduced on my side.  Closing, at least until it pops up again …

**Comment by ghost** [comment]
Hi, I recently encountered this bug. It works fine with cubic structure with soc, but it produces the error when I change it to tetragonal. I attached the struct file in case you want to reproduce the error.
[case.struct.txt](https://github.com/wien2wannier/wien2wannier/files/292884/case.struct.txt)

Related discussion on the Wien2k mailing list: http://zeus.theochem.tuwien.ac.at/pipermail/wien/2016-June/024930.html

**Comment by eassmann** [comment]
Seems to be fixed on master.
