### ISSUE TITLE
Bug in write_inwf

### ISSUE THREAD

**Issue by lengentyh** [wien2wannier/wien2wannier#16]
I am using the v2.0.0 of w2w. The error massages appears each time after executing the command 'write_inwf'.

File "/aracbox/app/WIEN2k/18.2/intel2018/write_inwf", line 58
    return np.array([float (s) for s in l[12:22], l[25:35], l[38:48]])
                                                ^
SyntaxError: invalid syntax

Besides, It seems to be other bugs in the source code.

**Comment by Ramesh2646** [comment]
i am also facing the same issue in Wein2k19.2.
File "/home/mcurie/WIEN2k_19.2/write_inwf", line 57
    return np.array([float (s) for s in l[12:22], l[25:35], l[38:48]])
                                                ^
SyntaxError: invalid syntax
Is there any way to solve this problem.

**Comment by lengentyh** [comment]
The problem is caused by using wrong version of python. I remember that the v2.0.0 w2w needs python 2 instead of python 3. Maybe you can try changing your python version.

**Comment by Ramesh2646** [comment]
Thanks a lot for your help. I will get back to you soon after trying this.
Thanks a lot

**Comment by rubel75** [comment]
it is solved in the new version of WIEN2k
